Repository OCA/product-variant, pull requests merged in 2020-11, with the labels that each got.

#187 [13.0][MIG] product_variant_default_code: Migration to 13.0
  product_variant_default_code/README.rst
  product_variant_default_code/__init__.py
  product_variant_default_code/__manifest__.py
  product_variant_default_code/data/ir_config_parameter.xml
  product_variant_default_code/demo/attribute_demo.xml
  product_variant_default_code/i18n/ar.po
  product_variant_default_code/i18n/ca.po
  product_variant_default_code/i18n/de.po
  product_variant_default_code/i18n/es.po
  product_variant_default_code/i18n/es_MX.po
  product_variant_default_code/i18n/fi.po
  product_variant_default_code/i18n/fr.po
  product_variant_default_code/i18n/fr_CH.po
  product_variant_default_code/i18n/hr.po
  product_variant_default_code/i18n/hr_HR.po
  product_variant_default_code/i18n/it.po
  product_variant_default_code/i18n/nl_NL.po
  product_variant_default_code/i18n/product_variant_default_code.pot
  product_variant_default_code/i18n/pt.po
  product_variant_default_code/i18n/pt_BR.po
  product_variant_default_code/i18n/ro.po
  product_variant_default_code/i18n/sl.po
  product_variant_default_code/i18n/tr_TR.po
  product_variant_default_code/i18n/vi_VN.po
  product_variant_default_code/i18n/zh_CN.po
  product_variant_default_code/models/__init__.py
  product_variant_default_code/models/config_settings.py
  product_variant_default_code/models/product.py
  product_variant_default_code/readme/CONFIGURATION.rst
  product_variant_default_code/readme/CONTRIBUTORS.rst
  product_variant_default_code/readme/DESCRIPTION.rst
  product_variant_default_code/readme/ROADMAP.rst
  product_variant_default_code/readme/USAGE.rst
  product_variant_default_code/security/product_security.xml
  product_variant_default_code/static/description/icon.png
  product_variant_default_code/static/description/index.html
  product_variant_default_code/tests/__init__.py
  product_variant_default_code/tests/test_variant_default_code.py
  product_variant_default_code/views/config_settings_view.xml
  product_variant_default_code/views/product_attribute_view.xml
  product_variant_default_code/views/product_view.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/product_variant_default_code/odoo/addons/product_variant_default_code
  setup/product_variant_default_code/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#189 [14.0][MIG] product_variant_default_code: Migration to 14.0
  product_variant_default_code/README.rst
  product_variant_default_code/__init__.py
  product_variant_default_code/__manifest__.py
  product_variant_default_code/data/ir_config_parameter.xml
  product_variant_default_code/demo/attribute_demo.xml
  product_variant_default_code/i18n/ar.po
  product_variant_default_code/i18n/ca.po
  product_variant_default_code/i18n/de.po
  product_variant_default_code/i18n/es.po
  product_variant_default_code/i18n/es_MX.po
  product_variant_default_code/i18n/fi.po
  product_variant_default_code/i18n/fr.po
  product_variant_default_code/i18n/fr_CH.po
  product_variant_default_code/i18n/hr.po
  product_variant_default_code/i18n/hr_HR.po
  product_variant_default_code/i18n/it.po
  product_variant_default_code/i18n/nl_NL.po
  product_variant_default_code/i18n/product_variant_default_code.pot
  product_variant_default_code/i18n/pt.po
  product_variant_default_code/i18n/pt_BR.po
  product_variant_default_code/i18n/ro.po
  product_variant_default_code/i18n/sl.po
  product_variant_default_code/i18n/tr_TR.po
  product_variant_default_code/i18n/vi_VN.po
  product_variant_default_code/i18n/zh_CN.po
  product_variant_default_code/models/__init__.py
  product_variant_default_code/models/config_settings.py
  product_variant_default_code/models/product.py
  product_variant_default_code/readme/CONFIGURATION.rst
  product_variant_default_code/readme/CONTRIBUTORS.rst
  product_variant_default_code/readme/DESCRIPTION.rst
  product_variant_default_code/readme/ROADMAP.rst
  product_variant_default_code/readme/USAGE.rst
  product_variant_default_code/security/product_security.xml
  product_variant_default_code/static/description/icon.png
  product_variant_default_code/static/description/index.html
  product_variant_default_code/tests/__init__.py
  product_variant_default_code/tests/test_variant_default_code.py
  product_variant_default_code/views/config_settings_view.xml
  product_variant_default_code/views/product_attribute_view.xml
  product_variant_default_code/views/product_view.xml
  setup/product_variant_default_code/odoo/addons/product_variant_default_code
  setup/product_variant_default_code/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#193 [13.0][IMP] product_variant_configurator: Add website_sale incompatibility to ROADMAP
  product_variant_configurator/readme/ROADMAP.rst
Labels: bot is merging ⏳
