Repository OCA/product-variant, pull requests merged in 2020-02, with the labels that each got.

#166 [FIX] sale_order_variant_mgmt: Filter attributes
  sale_order_variant_mgmt/tests/test_sale_order_variant_mgmt.py
  sale_order_variant_mgmt/wizard/sale_manage_variant.py
Labels: approved

#167 [FIX] broken test in sale_variant_configurator
  sale_variant_configurator/tests/test_sale_order.py
Labels: approved, needs review

#161 [ADD] product_variant_specific_tax
  product_variant_specific_tax/README.rst
  product_variant_specific_tax/__init__.py
  product_variant_specific_tax/__manifest__.py
  product_variant_specific_tax/i18n/product_variant_specific_tax.pot
  product_variant_specific_tax/models/__init__.py
  product_variant_specific_tax/models/product.py
  product_variant_specific_tax/models/sale_order_line.py
  product_variant_specific_tax/readme/CONTRIBUTORS.rst
  product_variant_specific_tax/readme/DESCRIPTION.rst
  product_variant_specific_tax/static/description/icon.png
  product_variant_specific_tax/static/description/index.html
  product_variant_specific_tax/tests/__init__.py
  product_variant_specific_tax/tests/test_sale_order.py
  product_variant_specific_tax/views/product_view.xml
Labels: approved, ready to merge
