Repository OCA/product-variant, pull requests merged in 2021-02, with the labels that each got.

#185 [13.0][MIG] purchase_variant_configurator
  purchase_variant_configurator/README.rst
  purchase_variant_configurator/__init__.py
  purchase_variant_configurator/__manifest__.py
  purchase_variant_configurator/hooks.py
  purchase_variant_configurator/i18n/es.po
  purchase_variant_configurator/i18n/fr.po
  purchase_variant_configurator/i18n/hr.po
  purchase_variant_configurator/i18n/it.po
  purchase_variant_configurator/i18n/pt_BR.po
  purchase_variant_configurator/i18n/purchase_variant_configurator.pot
  purchase_variant_configurator/i18n/ro.po
  purchase_variant_configurator/i18n/sl.po
  purchase_variant_configurator/models/__init__.py
  purchase_variant_configurator/models/purchase_order_line.py
  purchase_variant_configurator/readme/CONTRIBUTORS.rst
  purchase_variant_configurator/readme/DESCRIPTION.rst
  purchase_variant_configurator/static/description/icon.png
  purchase_variant_configurator/static/description/index.html
  purchase_variant_configurator/tests/__init__.py
  purchase_variant_configurator/tests/test_purchase_order.py
  purchase_variant_configurator/views/inherited_purchase_order_views.xml
  setup/purchase_variant_configurator/odoo/addons/purchase_variant_configurator
  setup/purchase_variant_configurator/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#205 [13.0][ADD] product_variant_attribute_tax: New module
  product_variant_attribute_tax/README.rst
  product_variant_attribute_tax/__init__.py
  product_variant_attribute_tax/__manifest__.py
  product_variant_attribute_tax/i18n/es.po
  product_variant_attribute_tax/i18n/product_variant_attribute_tax.pot
  product_variant_attribute_tax/models/__init__.py
  product_variant_attribute_tax/models/product_attribute_value.py
  product_variant_attribute_tax/readme/CONFIGURE.rst
  product_variant_attribute_tax/readme/CONTRIBUTORS.rst
  product_variant_attribute_tax/readme/DESCRIPTION.rst
  product_variant_attribute_tax/static/description/icon.png
  product_variant_attribute_tax/static/description/index.html
  product_variant_attribute_tax/views/product_attribute_views.xml
  setup/product_variant_attribute_tax/odoo/addons/product_variant_attribute_tax
  setup/product_variant_attribute_tax/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#207 [13.0][ADD] sale_product_variant_attribute_tax: New module
  sale_product_variant_attribute_tax/README.rst
  sale_product_variant_attribute_tax/__init__.py
  sale_product_variant_attribute_tax/__manifest__.py
  sale_product_variant_attribute_tax/models/__init__.py
  sale_product_variant_attribute_tax/models/sale_order.py
  sale_product_variant_attribute_tax/readme/CONTRIBUTORS.rst
  sale_product_variant_attribute_tax/readme/DESCRIPTION.rst
  sale_product_variant_attribute_tax/readme/USAGE.rst
  sale_product_variant_attribute_tax/static/description/icon.png
  sale_product_variant_attribute_tax/static/description/index.html
  sale_product_variant_attribute_tax/tests/__init__.py
  sale_product_variant_attribute_tax/tests/test_sale_product_variant_attribute_tax.py
  setup/sale_product_variant_attribute_tax/odoo/addons/sale_product_variant_attribute_tax
  setup/sale_product_variant_attribute_tax/setup.py
Labels: bot is merging ⏳

#206 [13.0][MIG] purchase_variant_configurator_on_confirm: Migration to 13.0
  purchase_variant_configurator_on_confirm/README.rst
  purchase_variant_configurator_on_confirm/__init__.py
  purchase_variant_configurator_on_confirm/__manifest__.py
  purchase_variant_configurator_on_confirm/i18n/ar.po
  purchase_variant_configurator_on_confirm/i18n/ca.po
  purchase_variant_configurator_on_confirm/i18n/de.po
  purchase_variant_configurator_on_confirm/i18n/es.po
  purchase_variant_configurator_on_confirm/i18n/es_MX.po
  purchase_variant_configurator_on_confirm/i18n/fi.po
  purchase_variant_configurator_on_confirm/i18n/fr.po
  purchase_variant_configurator_on_confirm/i18n/fr_CH.po
  purchase_variant_configurator_on_confirm/i18n/hr.po
  purchase_variant_configurator_on_confirm/i18n/hr_HR.po
  purchase_variant_configurator_on_confirm/i18n/it.po
  purchase_variant_configurator_on_confirm/i18n/nl_NL.po
  purchase_variant_configurator_on_confirm/i18n/pt_BR.po
  purchase_variant_configurator_on_confirm/i18n/purchase_variant_configurator_on_confirm.pot
  purchase_variant_configurator_on_confirm/i18n/ro.po
  purchase_variant_configurator_on_confirm/i18n/sl.po
  purchase_variant_configurator_on_confirm/i18n/tr_TR.po
  purchase_variant_configurator_on_confirm/i18n/vi_VN.po
  purchase_variant_configurator_on_confirm/i18n/zh_CN.po
  purchase_variant_configurator_on_confirm/models/__init__.py
  purchase_variant_configurator_on_confirm/models/product_product.py
  purchase_variant_configurator_on_confirm/models/product_supplierinfo.py
  purchase_variant_configurator_on_confirm/models/product_template.py
  purchase_variant_configurator_on_confirm/models/purchase_order.py
  purchase_variant_configurator_on_confirm/readme/CONTRIBUTORS.rst
  purchase_variant_configurator_on_confirm/readme/DESCRIPTION.rst
  purchase_variant_configurator_on_confirm/static/description/icon.png
  purchase_variant_configurator_on_confirm/static/description/index.html
  purchase_variant_configurator_on_confirm/tests/__init__.py
  purchase_variant_configurator_on_confirm/tests/test_purchase_order.py
  purchase_variant_configurator_on_confirm/views/inherited_purchase_order_views.xml
  setup/purchase_variant_configurator_on_confirm/odoo/addons/purchase_variant_configurator_on_confirm
  setup/purchase_variant_configurator_on_confirm/setup.py
Labels: bot is merging ⏳

#209 [13.0][IMP] product_variant_configurator: Use Many2oneReference + index
  product_variant_configurator/models/product_configurator_attribute.py
Labels: approved, bot is merging ⏳

#210 [14.0][FIX] product_variant_default_code: don't translate mask
  product_variant_default_code/models/product.py
Labels: approved, bot is merging ⏳

#211 [FIX] product_variant_default_code: fix onchange code value
  product_variant_default_code/models/product.py
  product_variant_default_code/tests/test_variant_default_code.py
Labels: approved, bot is merging ⏳
