Repository OCA/product-variant, pull requests merged in 2021-06, with the labels that each got.

#203 [MIG] 14.0 product_variant_sale_price
  product_variant_sale_price/README.rst
  product_variant_sale_price/__init__.py
  product_variant_sale_price/__manifest__.py
  product_variant_sale_price/hooks.py
  product_variant_sale_price/i18n/ca.po
  product_variant_sale_price/i18n/de.po
  product_variant_sale_price/i18n/el_GR.po
  product_variant_sale_price/i18n/es.po
  product_variant_sale_price/i18n/es_ES.po
  product_variant_sale_price/i18n/es_MX.po
  product_variant_sale_price/i18n/eu.po
  product_variant_sale_price/i18n/fi.po
  product_variant_sale_price/i18n/fr.po
  product_variant_sale_price/i18n/fr_CH.po
  product_variant_sale_price/i18n/fr_FR.po
  product_variant_sale_price/i18n/gl.po
  product_variant_sale_price/i18n/hr.po
  product_variant_sale_price/i18n/hr_HR.po
  product_variant_sale_price/i18n/it.po
  product_variant_sale_price/i18n/nl.po
  product_variant_sale_price/i18n/nl_NL.po
  product_variant_sale_price/i18n/product_variant_sale_price.pot
  product_variant_sale_price/i18n/pt.po
  product_variant_sale_price/i18n/pt_BR.po
  product_variant_sale_price/i18n/ro.po
  product_variant_sale_price/i18n/ru.po
  product_variant_sale_price/i18n/sk.po
  product_variant_sale_price/i18n/sl.po
  product_variant_sale_price/i18n/tr.po
  product_variant_sale_price/i18n/tr_TR.po
  product_variant_sale_price/i18n/vi_VN.po
  product_variant_sale_price/i18n/zh_CN.po
  product_variant_sale_price/models/__init__.py
  product_variant_sale_price/models/product_product.py
  product_variant_sale_price/readme/CONTRIBUTORS.rst
  product_variant_sale_price/readme/DESCRIPTION.rst
  product_variant_sale_price/static/description/icon.png
  product_variant_sale_price/static/description/index.html
  product_variant_sale_price/tests/__init__.py
  product_variant_sale_price/tests/test_product_product.py
  product_variant_sale_price/views/product_views.xml
  setup/product_variant_sale_price/odoo/addons/product_variant_sale_price
  setup/product_variant_sale_price/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#217 [14.0][MIG] sale_order_line_variant_description
  sale_order_line_variant_description/README.rst
  sale_order_line_variant_description/__init__.py
  sale_order_line_variant_description/__manifest__.py
  sale_order_line_variant_description/i18n/ar.po
  sale_order_line_variant_description/i18n/ca.po
  sale_order_line_variant_description/i18n/de.po
  sale_order_line_variant_description/i18n/el_GR.po
  sale_order_line_variant_description/i18n/es.po
  sale_order_line_variant_description/i18n/es_ES.po
  sale_order_line_variant_description/i18n/es_VE.po
  sale_order_line_variant_description/i18n/fi.po
  sale_order_line_variant_description/i18n/fr.po
  sale_order_line_variant_description/i18n/fr_CH.po
  sale_order_line_variant_description/i18n/fr_FR.po
  sale_order_line_variant_description/i18n/gl.po
  sale_order_line_variant_description/i18n/hr.po
  sale_order_line_variant_description/i18n/hr_HR.po
  sale_order_line_variant_description/i18n/it.po
  sale_order_line_variant_description/i18n/nl.po
  sale_order_line_variant_description/i18n/nl_NL.po
  sale_order_line_variant_description/i18n/pt.po
  sale_order_line_variant_description/i18n/pt_BR.po
  sale_order_line_variant_description/i18n/ro.po
  sale_order_line_variant_description/i18n/ru.po
  sale_order_line_variant_description/i18n/sale_order_line_variant_description.pot
  sale_order_line_variant_description/i18n/sl.po
  sale_order_line_variant_description/i18n/tr.po
  sale_order_line_variant_description/i18n/tr_TR.po
  sale_order_line_variant_description/i18n/vi_VN.po
  sale_order_line_variant_description/i18n/zh_CN.po
  sale_order_line_variant_description/models/__init__.py
  sale_order_line_variant_description/models/product_product.py
  sale_order_line_variant_description/models/sale_order_line.py
  sale_order_line_variant_description/readme/CONTRIBUTORS.rst
  sale_order_line_variant_description/readme/DESCRIPTION.rst
  sale_order_line_variant_description/static/description/icon.png
  sale_order_line_variant_description/static/description/index.html
  sale_order_line_variant_description/tests/__init__.py
  sale_order_line_variant_description/tests/test_sale_order_line_variant_description.py
  sale_order_line_variant_description/views/product_view.xml
  setup/sale_order_line_variant_description/odoo/addons/sale_order_line_variant_description
  setup/sale_order_line_variant_description/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#198 [13.0] product_variant_default_code improvements
  product_variant_default_code/models/product.py
  product_variant_default_code/readme/CONFIGURATION.rst
  product_variant_default_code/readme/CONTRIBUTORS.rst
  product_variant_default_code/readme/DESCRIPTION.rst
  product_variant_default_code/readme/USAGE.rst
  product_variant_default_code/views/product_attribute_view.xml
Labels: approved, bot is merging ⏳
