Repository OCA/product-variant, pull requests merged in 2022-10, with the labels that each got.

#265 [14.0][IMP] product_variant_inactive: remove activate button in the list view
  product_variant_inactive/models/product_variant.py
  product_variant_inactive/tests/test_button.py
  product_variant_inactive/views/product_variant_view.xml
Labels: approved, bot is merging ⏳

#266 [14.0][IMP] product_variant_inactive: When deactivating all variants, the product.template must be archived
  product_variant_inactive/models/product_template.py
  product_variant_inactive/tests/test_button.py
Labels: approved, ready to merge, bot is merging ⏳

#269 [13.0] [ADD] product_variant_configurator_manual_creation
  product_variant_configurator_manual_creation/README.rst
  product_variant_configurator_manual_creation/__init__.py
  product_variant_configurator_manual_creation/__manifest__.py
  product_variant_configurator_manual_creation/models/__init__.py
  product_variant_configurator_manual_creation/models/product_template.py
  product_variant_configurator_manual_creation/readme/CONTRIBUTORS.rst
  product_variant_configurator_manual_creation/readme/DESCRIPTION.rst
  product_variant_configurator_manual_creation/security/ir.model.access.csv
  product_variant_configurator_manual_creation/static/description/index.html
  product_variant_configurator_manual_creation/tests/__init__.py
  product_variant_configurator_manual_creation/tests/test_product_variant_configurator_manual_creation.py
  product_variant_configurator_manual_creation/views/product_template_view.xml
  product_variant_configurator_manual_creation/wizards/__init__.py
  product_variant_configurator_manual_creation/wizards/wizard_product_variant_configurator_manual_creation.py
  product_variant_configurator_manual_creation/wizards/wizard_product_variant_configurator_manual_creation_view.xml
  setup/product_variant_configurator_manual_creation/odoo/addons/product_variant_configurator_manual_creation
  setup/product_variant_configurator_manual_creation/setup.py
Labels: bot is merging ⏳

#263 [14.0][IMP] product_variant_inactive: Improved management of variants
  product_variant_inactive/README.rst
  product_variant_inactive/__manifest__.py
  product_variant_inactive/models/product_template.py
  product_variant_inactive/models/product_variant.py
  product_variant_inactive/tests/__init__.py
  product_variant_inactive/tests/test_product_variant_inactive.py
  product_variant_inactive/views/product_variant_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#273 [15.0] [MIG] product_variant_configurator_manual_creation
  product_variant_configurator_manual_creation/README.rst
  product_variant_configurator_manual_creation/__init__.py
  product_variant_configurator_manual_creation/__manifest__.py
  product_variant_configurator_manual_creation/i18n/product_variant_configurator_manual_creation.pot
  product_variant_configurator_manual_creation/models/__init__.py
  product_variant_configurator_manual_creation/models/product_template.py
  product_variant_configurator_manual_creation/readme/CONTRIBUTORS.rst
  product_variant_configurator_manual_creation/readme/DESCRIPTION.rst
  product_variant_configurator_manual_creation/security/ir.model.access.csv
  product_variant_configurator_manual_creation/static/description/icon.png
  product_variant_configurator_manual_creation/static/description/index.html
  product_variant_configurator_manual_creation/tests/__init__.py
  product_variant_configurator_manual_creation/tests/test_product_variant_configurator_manual_creation.py
  product_variant_configurator_manual_creation/views/product_template_view.xml
  product_variant_configurator_manual_creation/wizards/__init__.py
  product_variant_configurator_manual_creation/wizards/wizard_product_variant_configurator_manual_creation.py
  product_variant_configurator_manual_creation/wizards/wizard_product_variant_configurator_manual_creation_view.xml
  setup/product_variant_configurator_manual_creation/odoo/addons/product_variant_configurator_manual_creation
  setup/product_variant_configurator_manual_creation/setup.py
Labels: approved, ready to merge, bot is merging ⏳
