Repository OCA/product-variant, pull requests merged in 2022-11, with the labels that each got.

#256 [14.0][ADD] product_matrix_sticky_header
  product_matrix_sticky_header/__manifest__.py
  product_matrix_sticky_header/readme/CONFIGURATION.rst
  product_matrix_sticky_header/readme/CONTRIBUTORS.rst
  product_matrix_sticky_header/readme/DESCRIPTION.rst
  product_matrix_sticky_header/readme/ROADMAP.rst
  product_matrix_sticky_header/readme/USAGE.rst
  product_matrix_sticky_header/static/description/icon.png
  product_matrix_sticky_header/static/img/screenshot.gif
  product_matrix_sticky_header/static/src/js/section_and_note_widget.js
  product_matrix_sticky_header/static/src/scss/product_matrix.scss
  product_matrix_sticky_header/static/src/xml/product_matrix.xml
  product_matrix_sticky_header/views/assets.xml
  setup/product_matrix_sticky_header/odoo/addons/product_matrix_sticky_header
  setup/product_matrix_sticky_header/setup.py
Labels: needs review, bot is merging ⏳, stale

#275 [14.0] Update from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: approved

#276 [15.0] [MIG] sale_order_line_variant_description
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
  sale_order_line_variant_description/README.rst
  sale_order_line_variant_description/__init__.py
  sale_order_line_variant_description/__manifest__.py
  sale_order_line_variant_description/i18n/ar.po
  sale_order_line_variant_description/i18n/ca.po
  sale_order_line_variant_description/i18n/de.po
  sale_order_line_variant_description/i18n/el_GR.po
  sale_order_line_variant_description/i18n/es.po
  sale_order_line_variant_description/i18n/es_ES.po
  sale_order_line_variant_description/i18n/es_VE.po
  sale_order_line_variant_description/i18n/fi.po
  sale_order_line_variant_description/i18n/fr.po
  sale_order_line_variant_description/i18n/fr_CH.po
  sale_order_line_variant_description/i18n/fr_FR.po
  sale_order_line_variant_description/i18n/gl.po
  sale_order_line_variant_description/i18n/hr.po
  sale_order_line_variant_description/i18n/hr_HR.po
  sale_order_line_variant_description/i18n/it.po
  sale_order_line_variant_description/i18n/nl.po
  sale_order_line_variant_description/i18n/nl_NL.po
  sale_order_line_variant_description/i18n/pt.po
  sale_order_line_variant_description/i18n/pt_BR.po
  sale_order_line_variant_description/i18n/ro.po
  sale_order_line_variant_description/i18n/ru.po
  sale_order_line_variant_description/i18n/sale_order_line_variant_description.pot
  sale_order_line_variant_description/i18n/sl.po
  sale_order_line_variant_description/i18n/tr.po
  sale_order_line_variant_description/i18n/tr_TR.po
  sale_order_line_variant_description/i18n/vi_VN.po
  sale_order_line_variant_description/i18n/zh_CN.po
  sale_order_line_variant_description/models/__init__.py
  sale_order_line_variant_description/models/product_product.py
  sale_order_line_variant_description/models/sale_order_line.py
  sale_order_line_variant_description/readme/CONTRIBUTORS.rst
  sale_order_line_variant_description/readme/DESCRIPTION.rst
  sale_order_line_variant_description/static/description/icon.png
  sale_order_line_variant_description/static/description/index.html
  sale_order_line_variant_description/tests/__init__.py
  sale_order_line_variant_description/tests/test_sale_order_line_variant_description.py
  sale_order_line_variant_description/views/product_view.xml
  setup/sale_order_line_variant_description/odoo/addons/sale_order_line_variant_description
  setup/sale_order_line_variant_description/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
