Repository OCA/product-variant, pull requests merged in 2023-04, with the labels that each got.

#288 [14.0][FIX] product_variant_default_code: fix missing reference_mask …
  product_variant_default_code/models/product.py
Labels: approved, bot is merging ⏳

#271 [14.0] [MIG] product_variant_configurator_manual_creation
  product_variant_configurator_manual_creation/README.rst
  product_variant_configurator_manual_creation/__init__.py
  product_variant_configurator_manual_creation/__manifest__.py
  product_variant_configurator_manual_creation/i18n/product_variant_configurator_manual_creation.pot
  product_variant_configurator_manual_creation/models/__init__.py
  product_variant_configurator_manual_creation/models/product_template.py
  product_variant_configurator_manual_creation/readme/CONTRIBUTORS.rst
  product_variant_configurator_manual_creation/readme/DESCRIPTION.rst
  product_variant_configurator_manual_creation/security/ir.model.access.csv
  product_variant_configurator_manual_creation/static/description/icon.png
  product_variant_configurator_manual_creation/static/description/index.html
  product_variant_configurator_manual_creation/tests/__init__.py
  product_variant_configurator_manual_creation/tests/test_product_variant_configurator_manual_creation.py
  product_variant_configurator_manual_creation/views/product_template_view.xml
  product_variant_configurator_manual_creation/wizards/__init__.py
  product_variant_configurator_manual_creation/wizards/wizard_product_variant_configurator_manual_creation.py
  product_variant_configurator_manual_creation/wizards/wizard_product_variant_configurator_manual_creation_view.xml
  setup/product_variant_configurator_manual_creation/odoo/addons/product_variant_configurator_manual_creation
  setup/product_variant_configurator_manual_creation/setup.py
Labels: approved, bot is merging ⏳, stale

#283 product_variant_inactive: fix unlink variant
  product_variant_inactive/models/product_variant.py
  product_variant_inactive/tests/test_product_variant_inactive.py
Labels: bot is merging ⏳
